{
 "title": "Curió",
 "tags": [ "HOME" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "sigla", "label": "sigla", "query": "label_values(up,namespace)" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_container_info{sigla=~\"$sigla\",image=~\".*iib-curio.*\"},namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Visão Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Provimento Total [24h]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[24h])) + sum(delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Provimento Erro [24h]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Provimento - Req/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m])))"
    }
   ]
  },
  {
   "title": "Provimento - % de sucesso [24h]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[24h]))/sum(delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[24h]) + delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Latência p99",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(application_curio_provedor_sucesso_seconds{namespace=~\"$namespace\",quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "%  Pod Running",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase {phase=\"Running\",namespace=~\"$namespace\"} * on (pod) group_left sum (kube_pod_container_info{image=~\".*iib-curio.*\",namespace=~\"$namespace\"}) by (pod))\n/\n(\n  sum (kube_pod_status_phase {phase!=\"Running\",namespace=~\"$namespace\"} * on (pod) group_left sum (kube_pod_container_info{image=~\".*iib-curio.*\",namespace=~\"$namespace\"}) by (pod))\n  +\n  sum (kube_pod_status_phase {phase=\"Running\",namespace=~\"$namespace\"} * on (pod) group_left sum (kube_pod_container_info{image=~\".*iib-curio.*\",namespace=~\"$namespace\"}) by (pod)))"
    }
   ]
  },
  {
   "title": "Namespaces total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(kube_pod_container_info{namespace=~\"$namespace\",image=~\".*iib-curio.*\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespaces Mon.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace - links:",
   "type": "dashlist",
   "description": "Análise por operação do namespace",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 9 }
  },
  {
   "title": "Namespaces ",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 8, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",image=~\".*iib-curio.*\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",image=~\".*iib-curio.*\"}) by (namespace)"
    },
    {
     "expr": "count(sum(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}) by (namespace))by(namespace)"
    },
    {
     "expr": "count(sum(application_curio_consumidor_sucesso_seconds_count{namespace=~\"$namespace\"}) by (namespace))by(namespace)"
    }
   ]
  },
  {
   "title": "Versão",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",image=~\".*iib-curio.*\"}) by (image)",
     "legendFormat": "{{image}} - {{sigla}}"
    }
   ]
  },
  {
   "title": "Imagens",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",image=~\".*iib-curio.*\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Phase do pod",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "sum by (phase,sigla) (kube_pod_status_phase {phase!=\"Running\",namespace=~\"$namespace\"} * on (pod) group_left sum (kube_pod_container_info{image=~\".*iib-curio.*\",namespace=~\"$namespace\"}) by (pod)) > 0",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum by (phase) (kube_pod_status_phase {phase=\"Running\",namespace=~\"$namespace\"} * on (pod) group_left sum (kube_pod_container_info{image=~\".*iib-curio.*\",namespace=~\"$namespace\"}) by (pod)) > 0",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Provimento de iib",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}) by (operacao))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Consumo de iib",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(application_curio_consumidor_sucesso_seconds_count{namespace=~\"$namespace\"}) by (operacao))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "3GS - Provimento [10m]",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]))by (namespace) > 0"
    },
    {
     "expr": "sum(irate(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]))by (namespace) > 0"
    },
    {
     "expr": "sum(delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m]))by (namespace) > 0"
    },
    {
     "expr": "(\n  sum(\n    delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m])) \n  by (namespace)\n  /\n  sum(\n    delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m])\n     + \n    delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m])\n  )by (namespace)\n) > 0"
    },
    {
     "expr": "(\navg(avg_over_time(application_curio_provedor_sucesso_seconds{namespace=~\"$namespace\",quantile=\"0.99\"}[10m])) by (namespace) \n*\ncount(sum(delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]))by (namespace) > 0 ) by (namespace)\n) > 0"
    }
   ]
  },
  {
   "title": "3GS - Consumo operação iib [10m]",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(delta(application_curio_consumidor_sucesso_seconds_count{release_k8s_bb_sigla=~\"$sigla\"}[10m]))by (namespace) > 0"
    },
    {
     "expr": "sum(irate(application_curio_consumidor_sucesso_seconds_count{release_k8s_bb_sigla=~\"$sigla\"}[10m]))by (namespace) > 0"
    },
    {
     "expr": "sum(delta(application_curio_consumidor_erro_seconds_count{release_k8s_bb_sigla=~\"$sigla\"}[10m]))by (namespace) > 0"
    },
    {
     "expr": "(\n  sum(\n    delta(application_curio_consumidor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m])) \n  by (namespace)\n  /\n  sum(\n    delta(application_curio_consumidor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m])\n     + \n    delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m])\n  )by (namespace)\n) > 0"
    },
    {
     "expr": "(\navg(avg_over_time(application_curio_consumidor_sucesso_seconds{namespace=~\"$namespace\",quantile=\"0.99\"}[10m])) by (namespace) \n*\ncount(sum(delta(application_curio_consumidor_sucesso_seconds_count{release_k8s_bb_sigla=~\"$sigla\"}[10m]))by (namespace) > 0 ) by (namespace)\n) > 0"
    }
   ]
  },
  {
   "title": "3GS - Provimento [10m]",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]))by (operacao) > 0"
    },
    {
     "expr": "sum(irate(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]))by (operacao) > 0"
    },
    {
     "expr": "sum(delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m]))by (operacao) > 0"
    },
    {
     "expr": "(\n  sum(\n    delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m])) \n  by (operacao)\n  /\n  sum(\n    delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m])\n     + \n    delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m])\n  )by (operacao)\n) > 0"
    },
    {
     "expr": "(\navg(avg_over_time(application_curio_provedor_sucesso_seconds{namespace=~\"$namespace\",quantile=\"0.99\"}[10m])) by (operacao) \n*\ncount(sum(delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]))by (operacao) > 0 ) by (operacao)\n) > 0"
    }
   ]
  },
  {
   "title": "3GS - Consumo operação iib [10m]",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(delta(application_curio_consumidor_sucesso_seconds_count{release_k8s_bb_sigla=~\"$sigla\"}[10m]))by (operacao) > 0"
    },
    {
     "expr": "sum(irate(application_curio_consumidor_sucesso_seconds_count{release_k8s_bb_sigla=~\"$sigla\"}[10m]))by (operacao) > 0"
    },
    {
     "expr": "sum(delta(application_curio_consumidor_erro_seconds_count{release_k8s_bb_sigla=~\"$sigla\"}[10m]))by (operacao) > 0"
    },
    {
     "expr": "(\n  sum(\n    delta(application_curio_consumidor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m])) \n  by (operacao)\n  /\n  sum(\n    delta(application_curio_consumidor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m])\n     + \n    delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m])\n  )by (operacao)\n) > 0"
    },
    {
     "expr": "(\navg(avg_over_time(application_curio_consumidor_sucesso_seconds{namespace=~\"$namespace\",quantile=\"0.99\"}[10m])) by (operacao) \n*\ncount(sum(delta(application_curio_consumidor_sucesso_seconds_count{release_k8s_bb_sigla=~\"$sigla\"}[10m]))by (operacao) > 0 ) by (operacao)\n) > 0"
    }
   ]
  },
  { "title": "Request/segundo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Provedor - Req/s com curió",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m])))"
    }
   ]
  },
  {
   "title": "Consumidor - Req/s com curió",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(application_curio_consumidor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m])))"
    }
   ]
  },
  {
   "title": "Provedor - Req/s com curió por namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]))by (namespace) ) ",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Consumidor - Req/s com curió por namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(application_curio_consumidor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]))by (namespace) ) ",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Provedor - Req/s com curió por operação",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]))by (operacao) ) ",
     "legendFormat": "{{operacao}}"
    }
   ]
  },
  {
   "title": "Consumidor - Req/s com curió por operação",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(application_curio_consumidor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m])) by (namespace,operacao) ) ",
     "legendFormat": "{{namespace}} - {{operacao}}"
    }
   ]
  },
  {
   "title": "Taxa de erro",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Provimento - % de sucesso/10 min",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]))/sum(delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]) + delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m]))"
      }
     ]
    },
    {
     "title": "Provimento - Erros nos últimos 10 minutos",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m]))"
      }
     ]
    },
    {
     "title": "Provimento - % de erros/10 min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m]))/sum(delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]) + delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m]))*100",
       "legendFormat": "% de erro"
      }
     ]
    },
    {
     "title": "Provimento - Erros nos últimos 10 minutos",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Provimento - % de erros/10 min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m])) by (namespace)/sum(delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]) + delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m]))by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Provimento - Erros nos últimos 10 minutos por operacao",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m])) by (operacao)",
       "legendFormat": "{{operacao}}"
      }
     ]
    },
    {
     "title": "Provimento - % de erros/10 min por operacao",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m])) by (operacao)/sum(delta(application_curio_provedor_sucesso_seconds_count{namespace=~\"$namespace\"}[10m]) + delta(application_curio_provedor_erro_seconds_count{namespace=~\"$namespace\"}[10m]))by (operacao))",
       "legendFormat": "{{operacao}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latência",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latência p99 de sucesso <= 60s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(application_curio_provedor_sucesso_seconds{namespace=~\"$namespace\",quantile=\"0.99\"}) by (namespace) <= 60",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Latência p99 de sucesso <= 60s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(application_curio_provedor_sucesso_seconds{namespace=~\"$namespace\",quantile=\"0.99\"}) by (operacao) <= 60",
       "legendFormat": "{{operacao}}"
      }
     ]
    },
    {
     "title": "Latência p99 de sucesso > 60s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(application_curio_provedor_sucesso_seconds{namespace=~\"$namespace\",quantile=\"0.99\"}) by (namespace) > 60",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Saturação",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uso de Cpu do container curió por namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',container_name=\"curio-sidecar\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Uso de Memória do container curió por namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 119 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace',container_name=\"curio-sidecar\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}