{
 "title": "Detalhe do namespace",
 "tags": [ "K8s" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "sigla", "label": "sigla", "query": "label_values(up,namespace)" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{namespace=~\"$sigla.*\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}, node)"
   },
   {
    "name": "container",
    "label": "container",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Describe namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "content": "### HARD\n\n- Recursos disponíveis pro namespace escolhido"
    },
    {
     "title": "Pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"pods\",type=\"hard\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "CPU  limits",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "CPU  request",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"requests.cpu\",type=\"hard\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Memory limits",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"limits.memory\",type=\"hard\",namespace=\"$namespace\"} /1024^3"
      }
     ]
    },
    {
     "title": "Memória  request",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"requests.memory\",type=\"hard\",namespace=\"$namespace\"} / 1024^3"
      }
     ]
    },
    {
     "title": "Configmaps",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"configmaps\",type=\"hard\",namespace=\"$namespace\"} "
      }
     ]
    },
    {
     "title": "PVC",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"persistentvolumeclaims\",type=\"hard\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Storage  request",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"requests.storage\",type=\"hard\",namespace=\"$namespace\"} / 1024^3"
      }
     ]
    },
    {
     "title": "Secrets",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"secrets\",type=\"hard\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Services",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"services\",type=\"hard\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "content": "### USED\n\n- Recursos aprovisionados no namespace escolhido"
    },
    {
     "title": "Pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"pods\",type=\"used\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "CPU  limits",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"limits.cpu\",type=\"used\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "CPU  request",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Memory limits",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"limits.memory\",type=\"used\",namespace=\"$namespace\"} /1024^3"
      }
     ]
    },
    {
     "title": "Memória  request",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"requests.memory\",type=\"used\",namespace=\"$namespace\"} / 1024^3"
      }
     ]
    },
    {
     "title": "Configmaps",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"configmaps\",type=\"used\",namespace=\"$namespace\"} "
      }
     ]
    },
    {
     "title": "PVC",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"persistentvolumeclaims\",type=\"used\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Storage  request",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"requests.storage\",type=\"used\",namespace=\"$namespace\"} / 1024^3"
      }
     ]
    },
    {
     "title": "Secrets",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"secrets\",type=\"used\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Services",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_resourcequota{resource=\"services\",type=\"used\",namespace=\"$namespace\"}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 }, "content": "# %" },
    {
     "title": "pods",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"pods\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"pods\",type=\"hard\",namespace=\"$namespace\"}) * 100"
      }
     ]
    },
    {
     "title": "CPU limits",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 7 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100"
      }
     ]
    },
    {
     "title": "CPU Request",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 7 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100"
      }
     ]
    },
    {
     "title": "Memory limits",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 7 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.memory\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\",namespace=\"$namespace\"}) * 100"
      }
     ]
    },
    {
     "title": "Memory Request",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 7 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"requests.memory\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.memory\",type=\"hard\",namespace=\"$namespace\"}) * 100"
      }
     ]
    },
    {
     "title": "Configmaps",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 7 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"configmaps\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"configmaps\",type=\"hard\",namespace=\"$namespace\"}) * 100"
      }
     ]
    },
    {
     "title": "PVC",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 7 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"persistentvolumeclaims\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"persistentvolumeclaims\",type=\"hard\",namespace=\"$namespace\"}) * 100"
      }
     ]
    },
    {
     "title": "Storage Request",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 18, "y": 7 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"requests.storage\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.storage\",type=\"hard\",namespace=\"$namespace\"}) * 100"
      }
     ]
    },
    {
     "title": "Secrets",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 20, "y": 7 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"secrets\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"secrets\",type=\"hard\",namespace=\"$namespace\"}) * 100"
      }
     ]
    },
    {
     "title": "Secrets",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"services\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"services\",type=\"hard\",namespace=\"$namespace\"}) * 100"
      }
     ]
    },
    {
     "title": "Pod",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "count(kube_pod_labels{namespace=\"$namespace\"}) by (label_app,label_deploy)"
      }
     ]
    },
    {
     "title": "Imagens",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 11, "x": 6, "y": 11 },
     "targets": [
      {
       "expr": "count(kube_pod_container_info{namespace=\"$namespace\"}) by (container,image)"
      }
     ]
    },
    {
     "title": "Escalabilidade horizontal",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 11 },
     "targets": [
      {
       "expr": "sum(kube_hpa_spec_min_replicas{namespace=\"$namespace\"}) by (hpa)"
      },
      {
       "expr": "sum(kube_hpa_spec_max_replicas{namespace=\"$namespace\"}) by (hpa)"
      }
     ]
    },
    {
     "title": "Services",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum(kube_service_spec_type{namespace=\"$namespace\"}) by (service,type) "
      }
     ]
    },
    {
     "title": "Secret",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 9, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "sum(kube_secret_info{namespace=\"$namespace\"}) by (secret) "
      }
     ]
    },
    {
     "title": "Ingress (só aparecerá se tiver sido acionado)",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 15 },
     "targets": [
      {
       "expr": "sum(nginx_ingress_controller_bytes_sent_count{namespace=\"$namespace\"}) by (host) "
      }
     ]
    }
   ]
  },
  {
   "title": "Métricas de Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingress (só aparecerá se tiver sido acionado)",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(nginx_ingress_controller_bytes_sent_count{namespace=\"$namespace\"}) by (ingress,host) ",
       "legendFormat": "{{  ingress  }}  - {{ host  }}"
      }
     ]
    },
    {
     "title": "Volume req/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespace\"}[2m])) by (host),0.001)",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Taxa de erros",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespace\",status!~\"2.*\"}[2m])) by (host)\n/\nsum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespace\"}[2m])) by (host)",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Erros por Return code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespace\",status!~\"2.*\"}[2m])) by (host,status),0.001)",
       "legendFormat": "{{ host }} -  {{  status  }}"
      }
     ]
    },
    {
     "title": "Latência de sucesso",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",status=~\"2.*\"}[2m])) by (le,host))",
       "legendFormat": "{{  host  }} - P50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",status=~\"2.*\"}[2m])) by (le,host))",
       "legendFormat": "{{  host  }} - P90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",status=~\"2.*\"}[2m])) by (le,host))",
       "legendFormat": "{{  host  }} - P99"
      }
     ]
    },
    {
     "title": "Latência de erro",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",status!~\"2.*\"}[2m])) by (le,host))",
       "legendFormat": "{{  host  }} - P50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",status!~\"2.*\"}[2m])) by (le,host))",
       "legendFormat": "{{  host  }} - P90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",status!~\"2.*\"}[2m])) by (le,host))",
       "legendFormat": "{{  host  }} - P99"
      }
     ]
    },
    {
     "title": "Tráfego",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_ingress_controller_request_size_sum{namespace=~\"$namespace\"}[2m])) by (host)",
       "legendFormat": "Recebido"
      },
      {
       "expr": "sum(irate(nginx_ingress_controller_response_size_sum{namespace=~\"$namespace\"}[2m])) by (host)",
       "legendFormat": "Enviado "
      }
     ]
    }
   ]
  },
  {
   "title": "Recursos por namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods em execução",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "CPU Usage by namespace",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~'${namespace:regex}',container_name!=\"POD\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Usage by namespace",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~'${namespace:regex}', container_name!=\"POD\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Storage by namespace",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (namespace) (container_fs_usage_bytes {namespace=~'${namespace:regex}', container_name!=\"POD\"}))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (namespace) (rate(container_network_receive_bytes_total{job=\"kubelet\", namespace=~'${namespace:regex}'}[1m])))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Recursos por pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods em execução",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_info{namespace=~\"$namespace\", pod=~'$pod', node=~\"$node\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage by pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~'${namespace:regex}', pod_name=~'${pod:regex}', container_name!=\"POD\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage by pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~'${namespace:regex}', pod_name=~'${pod:regex}', container_name!=\"\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{job=\"kubelet\", pod_name=~'${pod:regex}', namespace=~'${namespace:regex}'}[1m])))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Storage by pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (container_fs_usage_bytes {namespace=~'${namespace:regex}',pod_name=~'${pod:regex}', container_name!=\"POD\"}))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Storage solicitado por pvc",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (persistentvolumeclaim) (kube_persistentvolumeclaim_resource_requests_storage_bytes {namespace=~'${namespace:regex}'}))",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\",pod_name=~'${pod:regex}'}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~'${pod:regex}'}) by (pod)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\",pod_name=~'${pod:regex}'}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (pod)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\",pod_name=~'${pod:regex}'}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Quota by pod",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=~\"$namespace\",pod_name=~'${pod:regex}', container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (pod)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=~\"$namespace\",pod_name=~'${pod:regex}',container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (pod)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",pod_name=~'${pod:regex}',container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~'${pod:regex}'}) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "Recursos por node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\", node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 3, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\", node=~\"$node\"}) by (pod,node)"
      }
     ]
    },
    {
     "title": "Pods em execução",
     "type": "graph",
     "gridPos": { "h": 6, "w": 13, "x": 11, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$pod\", node=~\"$node\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Saturação de CPU do node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node:node_cpu_saturation_load1:{node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory Usage by node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~'${namespace:regex}', pod_name=~'${pod:regex}', node=~'$node', container_name!=\"POD\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  { "title": "Recursos por container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage by container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~'${namespace:regex}', pod_name=~'${pod:regex}',container_name=~'${container:regex}', container_name!=\"POD\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'${namespace:regex}', pod_name=~'${pod:regex}',container_name=~'${container:regex}', container_name!=\"POD\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Storage por container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (container_name) (container_fs_usage_bytes {namespace=~'${namespace:regex}',pod_name=~'${pod:regex}',container_name=~'${container:regex}',container_name!=\"POD\"}))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (node) (rate(container_network_receive_bytes_total{job=\"kubelet\", pod_name=~'${pod:regex}', namespace=~'${namespace:regex}',node=~'$node'}[1m])))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}