{
 "title": "Four Golden Signals",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Namespace", "label": "Namespace", "query": "label_values(up, namespace)" },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(up{namespace=\"$Namespace\"}, pod)"
   },
   {
    "name": "timerange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": " ${Namespace}",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{namespace=~\"$Namespace\"})",
     "legendFormat": "{{serviceVersion}}"
    }
   ]
  },
  {
   "title": "Trafego Médio",
   "type": "singlestat",
   "description": "Média de tráfego nos pods",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(http_requests_seconds_summary_count{namespace=~\"$Namespace\"}[$timerange]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "rqps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trafego Total",
   "type": "singlestat",
   "description": "Tráfego total nos pods",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(http_requests_seconds_summary_count{namespace=~\"$Namespace\"}[$timerange]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Requisições",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(http_requests_seconds_summary_count{namespace=~\"$Namespace\"}[$timerange]))"
    }
   ]
  },
  {
   "title": "Erros",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(http_requests_seconds_summary_count{namespace=~\"$Namespace\",status!=\"200\"}[$timerange]))"
    }
   ]
  },
  {
   "title": "Erros %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(http_requests_seconds_summary_count{namespace=~\"$Namespace\",status!=\"200\"}[$timerange]))/sum(delta(http_requests_seconds_summary_count{namespace=~\"$Namespace\"}[$timerange]))*100"
    }
   ]
  },
  {
   "title": "Latência Média",
   "type": "singlestat",
   "description": "Latência média das requisições nos pods",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(http_requests_seconds_summary_sum{namespace=~\"$Namespace\"}/http_requests_seconds_summary_count{namespace=~\"$Namespace\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memória Máxima",
   "type": "singlestat",
   "description": "Máximo consumo de memória no período",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(dev_typescript_nodejs_heap_size_used_bytes{namespace=~\"$Namespace\"}[$timerange]))/max(max_over_time(dev_typescript_nodejs_heap_size_total_bytes{namespace=~\"$Namespace\"}[$timerange]))*100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Gráficos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Latência Aplicação",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_requests_seconds_summary_sum{namespace=~\"$Namespace\"}/http_requests_seconds_summary_count{namespace=~\"$Namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Quantidade de Pods Ativo",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{namespace=~\"$Namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latency Percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(http_requests_seconds_summary_count{pod=~\"$Pod\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Memory - Used Heap x MaxHeap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "dev_typescript_nodejs_heap_size_used_bytes{namespace=~\"$Namespace\",pod=~\"$Pod\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "dev_typescript_nodejs_heap_size_total_bytes{namespace=~\"$Namespace\",pod=~\"$Pod\",endpoint=\"app\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}