{
 "title": "K8s - Visao Cluster",
 "tags": [ "K8s" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "sigla", "label": "sigla", "query": "label_values(up,namespace)" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_resourcequota{sigla=~\"$sigla\",resource=\"requests.memory\",type=\"used\"},namespace)"
   },
   {
    "name": "namespaceUsed",
    "label": "namespaceUsed",
    "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\"},namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespaceUsed\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Namespaces Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_namespace_created{namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Namespaces com deploy",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_namespace_created{namespace=~\"$namespaceUsed\"})",
     "legendFormat": "Namespaces Com deploy"
    }
   ]
  },
  {
   "title": "% de namespaces com deploy",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 11, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_namespace_created{namespace=~\"$namespaceUsed\"}) / count(kube_namespace_created{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Namespaces criados nos últimos 7 dias",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count ((time() - kube_namespace_created{namespace=~\"$namespace\"}) / (60*24) < (24*7))",
     "legendFormat": "Com deploy"
    }
   ]
  },
  {
   "title": "Pods Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase {namespace=~\"$namespace\"} > 0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pods em execução",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase {phase=~\"Running|Succeeded\",namespace=~\"$namespaceUsed\"}> 0) \n/ \nsum (kube_pod_status_phase {namespace=~\"$namespaceUsed\"} > 0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase {namespace=~\"$namespace\",phase!~\"Running|Succeeded\"} > 0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container_name!=\"POD\",container_name=~\".+\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"secrets\",type=\"used\",namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"services\",type=\"used\",namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Configmaps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"configmaps\",type=\"used\",namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Storage Req.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.storage\",type=\"used\",namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(nginx_ingress_controller_bytes_sent_count{namespace=~\"$namespace\"}) by (host))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Req/s ingress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespace\"}[40s])),0.001)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Taxa de erro ingress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespaceUsed\",status!~\"2.*\"}[2m])) /sum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespaceUsed\"}[2m])) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Latência Sucesso - P99",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",status=~\"2.*\"}[2m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Latência Erro - P99",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",status!~\"2.*\"}[2m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Mem Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\",type=\"used\",namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Mem Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 17 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\",type=\"used\",namespace=~\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.memory\",type=\"used\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Mem Uso",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 17 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\",container_name!=\"POD\",container_name=~\".+\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Mem Uso/Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 17 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{namespace=~\"$namespaceUsed\",container_name!=\"POD\",container_name=~\".+\"})) / (sum(kube_resourcequota{resource=\"requests.memory\",type=\"used\",namespace=~\"$namespaceUsed\"}))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Alvo Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 17 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{namespace=~\"$namespaceUsed\",container_name!=\"POD\",container_name=~\".+\"}) * 100 / 40)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cpu Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cpu Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 17 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=~\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.cpu\",type=\"used\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cpu Uso",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\",container_name!=\"POD\",container_name=~\".+\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cpu Uso/Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 17 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespaceUsed\",container_name!=\"POD\",container_name=~\".+\"})/sum(kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=~\"$namespaceUsed\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Alvo req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\",container_name!=\"POD\",container_name=~\".+\"})  * 100 / 40",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}