{
 "title": "K8s - Visao Geral",
 "tags": [ "K8s" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "sigla", "label": "sigla", "query": "label_values(up,namespace)" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_resourcequota{sigla=~\"$sigla\",resource=\"requests.memory\",type=\"used\"},namespace)"
   },
   {
    "name": "namespaceUsed",
    "label": "namespaceUsed",
    "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\"},namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespaceUsed\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_namespace_created{namespace=~\"$namespace\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "% com deploy",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 4, "x": 3, "y": 1 },
     "targets": [
      {
       "expr": "count(kube_namespace_created{namespace=~\"$namespaceUsed\"}) / count(kube_namespace_created{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 17, "x": 7, "y": 1 },
     "targets": [
      {
       "expr": "(kube_namespace_created{namespace=~\"$namespace\"} *1000)"
      },
      {
       "expr": "count(kube_namespace_created{namespace=~\"$namespaceUsed\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\",namespace=~\"$namespace\"} /1024^3) by (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{resource=\"requests.memory\",type=\"hard\",namespace=~\"$namespace\"} /1024^3) by (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=~\"$namespace\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{resource=\"requests.cpu\",type=\"hard\",namespace=~\"$namespace\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_resourcequota{resource=\"secrets\",type=\"hard\",namespace=~\"$namespace\"}) by (namespace)"
      }
     ]
    },
    {
     "title": "Com deploy",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_namespace_created{namespace=~\"$namespaceUsed\"})",
       "legendFormat": "Com deploy"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (kube_pod_status_phase {namespace=~\"$namespace\"} > 0)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 16, "x": 2, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(topk(10,sum (kube_pod_status_phase {namespace=~\"$namespace\"} > 0) by (namespace)))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Namespace/Phase",
     "type": "table-old",
     "gridPos": { "h": 15, "w": 6, "x": 18, "y": 2 },
     "targets": [
      {
       "expr": "sort_desc(topk(20,sum(kube_pod_status_phase{namespace=~\"$namespace\"}) by (namespace,phase) > 0))",
       "legendFormat": "{{sigla}}"
      }
     ]
    },
    {
     "title": "Pods Running",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Running  por Sigla",
     "type": "graph",
     "gridPos": { "h": 5, "w": 16, "x": 2, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"}) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Pods not Running",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase!=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Not Running ",
     "type": "graph",
     "gridPos": { "h": 5, "w": 16, "x": 2, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(kube_pod_status_phase{namespace=~\"$namespace\", phase!=\"Running\"}) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Pod Detalhes",
     "type": "table-old",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by (_0_namespace, _1_pod_name, _2_pod_ip, _3_node, _4_host_ip) \n(\n  label_replace(\n  label_replace(\n  label_replace(\n  label_replace(\n  label_replace(\n      kube_pod_info{namespace=~\"$namespace\"}\n  , \"_0_namespace\", \"$1\", \"namespace\", \"(.*)\")\n  , \"_1_pod_name\", \"$1\", \"pod_name\", \"(.*)\")  \n  , \"_2_pod_ip\", \"$1\", \"pod_ip\", \"(.*)\")    \n  , \"_3_node\", \"$1\", \"node\", \"(.*)\")\n  , \"_4_host_ip\", \"$1\", \"host_ip\", \"(.*)\")  \n)"
      },
      {
       "expr": "\nsum by (_0_namespace, _1_pod_name, label_chart_release_k8s_bb_version) (  \nlabel_replace(  \nlabel_replace(  \n\nkube_pod_labels{namespace=~\"$namespace\"}  \n\n, \"_0_namespace\", \"$1\", \"namespace\", \"(.*)\")  \n, \"_1_pod_name\", \"$1\", \"pod_name\", \"(.*)\")\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Running",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container_name!=\"POD\",container_name=~\".+\"})"
      }
     ]
    },
    {
     "title": "Containers Running por Sigla",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(count(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container_name!=\"POD\",container_name=~\".+\"}) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "count(kube_pod_container_info{namespace=~\"$namespace\"}) by (namespace,container,image)"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Req/s ingress",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
     "format": "reqps",
     "valueName": "current",
     "targets": [
      {
       "expr": "round(sum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespace\"}[40s])),0.001)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Req/s ingress",
     "type": "graph",
     "gridPos": { "h": 6, "w": 21, "x": 3, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(sum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespace\"}[40s])) by (namespace),0.001)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Taxa de erro ingress",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespaceUsed\",status=~\"4.*|5.*\"}[2m])) /sum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespaceUsed\"}[2m])) ",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Taxa de erro ingress",
     "type": "graph",
     "gridPos": { "h": 6, "w": 21, "x": 3, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespaceUsed\",status=~\"4.*|5.*\"}[2m])) by (namespace)/sum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=~\"$namespaceUsed\"}[2m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Latência Sucesso - P99",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",status=~\"2.*\"}[2m])) by (le))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Latência Sucesso - P99",
     "type": "graph",
     "gridPos": { "h": 6, "w": 21, "x": 3, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",status=~\"2.*\"}[2m])) by (le,namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Latência Erro - P99",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",status=~\"4.*|5.*\"}[2m])) by (le))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Latência Erro - P99",
     "type": "graph",
     "gridPos": { "h": 6, "w": 21, "x": 3, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\",status=~\"4.*|5.*\"}[2m])) by (le,namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request de Memória e CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Quota",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\",pod_name=~'${pod:regex}'}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Quota by pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\",pod_name=~'${pod:regex}', container_name!=\"\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_resourcequota{namespace=~\"$namespace\",resource=\"pods\",type=\"used\"}) by (namespace) > 0"
      },
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\",pod_name=~'${pod:regex}'}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (namespace)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\",pod_name=~'${pod:regex}'}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (namespace) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (namespace)"
      },
      {
       "expr": "sort_desc(sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\",pod_name=~'${pod:regex}'}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (namespace) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (namespace))"
      },
      {}
     ]
    },
    {
     "title": "Memory Quota by pod",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_resourcequota{namespace=~\"$namespace\",resource=\"pods\",type=\"used\"}) by (namespace) > 0"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=~\"$namespace\",pod_name=~'${pod:regex}', container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (namespace)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=~\"$namespace\",pod_name=~'${pod:regex}',container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (namespace) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\",pod=~'${pod:regex}'}) by (namespace)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",pod_name=~'${pod:regex}',container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (namespace) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~'${pod:regex}'}) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoração",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods dos namespaces de monitoração",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum (kube_pod_info{sigla=~\"$sigla\",pod_name=~\"prometheus-.*\"})  by (namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum (kube_pod_info{sigla=~\"$sigla\",pod_name=~\"alertmanager-.*\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum (kube_pod_info{sigla=~\"$sigla\",pod_name=~\".*grafana.*\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum (kube_pod_info{sigla=~\"$sigla\",pod_name=~\".*omi.*\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum (kube_pod_info{sigla=~\"$sigla\",pod_name=~\".*msteams.*\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}